### PR TITLE
Include LICENSE in pip package

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by rgieseke** [comment]
Thanks!

**Comment by jan-janssen** [comment]
@rgieseke By the way I created a conda-forge package are you interested to join me as maintainer? https://github.com/conda-forge/cite-feedstock

**Comment by rgieseke** [comment]
Yeah, i saw that! Thanks for that, i also did a new release which should includes the License.
I'm grateful that you maintain that and am happy to make any changes you might need, but i'm trying to keep the things i have to feel responsible for low.
In my experience and where i said yes to being a co-maintainer, conda updates are working fairly automatic but if not i just don't want to be the person who feels they need to fix it :-)

**Comment by jan-janssen** [comment]
sounds good to me

**Comment by rgieseke** [comment]
Added a conda badge! https://github.com/rgieseke/cite
:rocket: Thanks again for maintaining this!

**Pull request merged**
